spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/item_db
    username: postgres
    password: 1488

  flyway:
    failOnMissingLocations: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

server.port: 8001
---
spring:
  config:
    activate.on-profile: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate.on-profile: k8s
eureka:
  client:
    serviceUrl:
      defaultZone: //eureka-server:8761/eureka/