spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: postgres
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/